unhindered-ec/unhindered-ec

- .vscode/settings.json
- Planning.md
- README.md
- src/bitstring.rs
- src/generation.rs
- src/lib.rs
- src/population.rs
`esitsu@Twitch` suggested creating a `Generation` type that wraps a population and is in charge of things like selection and recombination. That sounded like a good idea, so we spent most of the 21 Sep 2022 stream getting that to work.
I also created a new `Planning.md` document to keep track of plans, goals, and what's happened. Should have been doing this on all the live streaming repos from the beginning.
> Create `Generation` type

- Cargo.lock
- Cargo.toml
- Planning.md
- benches/construction_benchmark.rs
- src/args.rs
- src/bin/main.rs
- src/generation.rs
- src/lib.rs
This adds a serial `Generation::next()` method so we can do runs serially as well as in parallel. 
I also at least started adding command line arguments using the `clap` crate. There's nothing here yet for selectors or the mutation/recombination pipeline. There's sort of support for the target problem, but you have to choose from a fairly small set of fixed options (just Count Ones and HIFF).
I used these to extend the benchmarking so we can benchmark full runs in four ways (serial vs. parallel, Count Ones vs. HIFF).
> Add serial `Generation::next()`, command line arguments, and extend benchmarking

- .github/workflows/ci.yml
- packages/ec-core/src/generator/collection.rs
- packages/push/src/push_vm/stack.rs
This is arguably pretty aggressive. I think it will straight up fail if either `cargo clippy` or `cargo fmt --check` fail, which might be more than we want. I figured I'd start with a very strict version, and then we can relax things later.
This closes #19
> Add GitHub ci

- packages/ec-core/src/generator/collection.rs
- packages/ec-core/src/test_results.rs
- packages/ec-ga-cli/src/main.rs
- packages/ec-linear/src/genome/demo_scorers.rs
- packages/ec-push-cli/src/main.rs
- packages/push/src/push_vm/stack.rs
- packages/rust-lexicase/src/lib.rs
This makes both the `Score` and `Error` types generic in some type `T` instead of having them both hard-coded to be `i64` values.
This also make `TestResult` generic in two types, one for errors and one for scores. Not entirely sure if we'll ever use that, but it seemed a potentially nice piece of flexibility.
When switching from `i64`, which is `Clone + Copy` to generic `T`, we didn't want to assume the ability to `Clone` or `Copy`, so we changed summation over references to require `T: ToOwned` so we could use `.to_owned()` to convert references to owned types.
We also removed the `From<&T>` impls. They weren't being used, and getting them to work would require adding constraints on `T` that didn't seem necessary or desirable at this point. Callers should call `.copy()`/`.copied()`, or …
> Genericize score and error

- packages/ec-core/src/operator/selector/lexicase.rs
- packages/ec-linear/src/genome/bitstring.rs
- packages/ec-push-cli/src/main.rs
- packages/push-macros/src/push_state/printing/generate_builder.rs
- packages/push/src/error/mod.rs
- packages/push/src/instruction/bool.rs
- packages/push/src/instruction/float.rs
- packages/push/src/instruction/int.rs
- packages/push/src/instruction/mod.rs
- packages/push/src/push_vm/mod.rs
- packages/push/src/push_vm/push_state.rs
- packages/push/src/push_vm/stack.rs
- packages/push/tests/int.rs
Use i64 instead as discussed in #13  ( Closes #13 )
>  Remove the `PushInteger` type

- packages/push-macros/src/push_state/printing/generate_builder.rs
All doctests were using `int_stack` for the variable name before, now it uses the correct stack type depending on the stack the tests are generated for.
> Use proper variable name in doctests

- packages/push/src/list_into.rs
Use into instead of from inside _into! macros to allow types that only impl into, not from, fix empty array macro, add tests
> Improve the `vec_into!` and `arr_into!` macros

- packages/ec-core/src/generator/collection.rs
- packages/ec-core/src/generator/mod.rs
- packages/ec-core/src/individual/ec.rs
- packages/ec-linear/src/genome/bitstring.rs
- packages/push/examples/complex_regression/main.rs
- packages/push/src/genome/plushy.rs
The primary goal of this PR is to improve the mechanisms for constructing generators, so we can chain them as is now done in `packages/push/examples/complex_regression/main.rs`.
We added constructors (`::new()`) and factory methods for both `CollectionGenerator` and `IndividualGenerator`. The factory methods allow us to chain generator construction in a nice way, avoiding the need for a bunch of intermediate variables.
We also created implementations of `Generator` for references (mutable and immutable) to `Generator`, which allows us to pass references to generators around and they can be used as "actual" generators.
In the process we found (and fixed, largely thanks to esitsu@Twitch!) a "bug" in `Bitstring` and `Plushy` where their implementations of `CollectionGenerator` were overly …
> Improve creation of generators

- .helix/languages.toml
- .vscode/settings.json
- CONTRIBUTING.md
@NicMcPhee make sure your rustfmt-unstable version is recent enough, I only added automatic config detection in the workspace recently, I don't know if it was already present when we tested it. (`cargo install rustfmt-unstable`)
> Configure vscode to use our rustfmt config

- packages/ec-core/src/individual/mod.rs
The old generate trait was deprecated but never actually removed, so this does that
> Remove old generate trait

- Cargo.lock
- packages/ec-linear/Cargo.toml
It turned out we never actually ended up using quickcheck (I think, ci will tell) so I just removed it
Closes #92
> Remove unused quickcheck dependency

- packages/ec-core/src/individual/ec.rs
- packages/ec-core/src/individual/scorer.rs
- packages/ec-core/src/operator/genome_scorer.rs
- packages/ec-ga-cli/src/main.rs
- packages/ec-push-cli/src/main.rs
- packages/push/examples/complex_regression/main.rs
- packages/push/src/evaluation/cases.rs
- packages/push/src/evaluation/mod.rs
- packages/push/src/lib.rs
- packages/push/tests/cases.rs
This introduces new `Case` and `Cases` types to represent training and testing cases, with a lot of trait implementations to converting to/from both `Case` and `Cases`.
We also introduced a new `FnScorer` struct that implements `Scorer`, which now has the `Output` type as an associated type instead of a generic.
`GenomeScorer` now takes a `Scorer` instead of a "raw" `Fn` for the scoring function.
These led to a variety in other dependent files and types.
> Generalize scorer & training/testing cases

- Cargo.lock
- Cargo.toml
- packages/ec-core/src/distributions/choices.rs
- packages/ec-core/src/distributions/mod.rs
- packages/ec-core/src/distributions/wrappers/owned.rs
- packages/ec-core/src/distributions/wrappers/slice_cloning.rs
- packages/ec-core/src/operator/selector/random.rs
- packages/ec-core/src/operator/selector/tournament.rs
- packages/ec-core/src/operator/selector/weighted.rs
- packages/push/examples/complex_regression/main.rs
- packages/push/examples/simple_regression/main.rs
- packages/push/src/genome/plushy.rs
This is meant to implement the `.into_gene_generator(CloseProbability::Uniform)` and `.to_gene_generator(CloseProbability::Given(0.1))` methods, but is currently waiting on https://github.com/rust-random/rand/pull/1402
( oh and as this is based on #94 the changelog is quite messy, see [here](https://github.com/JustusFluegel/rust-ga/compare/rand_distrb_trait...JustusFluegel:rust-ga:gene_generator_creation) for the direct diff )
>  Gene generator creation

- Cargo.lock
- Cargo.toml
- packages/push/Cargo.toml
- packages/push/src/instruction/bool.rs
- packages/push/src/push_vm/program.rs
- packages/push/src/push_vm/push_state.rs
- packages/push/tests/float.rs
- packages/push/tests/int.rs
Move all proptests from `proptest!{}` macros to using `#[test_strategy::proptest]`, this has several advantages:
- rustfmt works on attribute macros but not function-style macros: proptest can now be auto-formatted
- syn can parse attribute macros just fine where function-style macros need custom logic: allows us to use the same tools for minimizing max_stack_size without huge modifications to the tool
After moving to test_strategy I ran my capacity_optimizer script ( see the unhindered-ec org [here](https://github.com/unhindered-ec/capacity_optimizer)  ) and minimized the max_stack_sizes in the builder.
> Move from proptest!{} to test_strategy::proptest and update max_stack_size values

- packages/push/examples/complex_regression/main.rs
- packages/push/src/instruction/exec/dup_block.rs
- packages/push/src/instruction/exec/ifelse.rs
- packages/push/src/instruction/exec/mod.rs
- packages/push/src/instruction/exec/noop.rs
- packages/push/src/instruction/exec/unless.rs
- packages/push/src/instruction/exec/when.rs
This derives `strum::EnumIter` for `ExecInstruction`. For this to work, though, I had to also derive `Default` all the "sub-types" (e.g., `When`). That arguably should be been done before. While I was there, I also derived `Copy` for those that didn't already have it.
I also switched `complex_regression/main.rs` to use the new `Display` for individuals instead of `Debug` as before.
> Derive `EnumIter` for `ExecInstruction`

- packages/push/examples/complex_regression/main.rs
- packages/push/examples/simple_regression/main.rs
- packages/push/src/evaluation/cases.rs
- packages/push/tests/cases.rs
I think this is more consistent with some other naming we've done, and it was what I imagined this would be called when I was trying to find it while doing some other refactoring.
> Rename `WithTarget` with `WithTargetFn`

- .github/workflows/ci.yml
This ensures that all three toolchains will run even if one of them fails. Currently if `nightly` fails, then that can prevent either `stable` or `beta` from running to completion.
> Set GitHub Actions `fail-fast` to `false`

- Cargo.lock
- Cargo.toml
- packages/ec-core/Cargo.toml
- packages/ec-core/benches/test_results.rs
This adds some simple Criterion benchmarks for the `TestResults` type. The goal is to have the ability to measure the performance of the `TestResults` implementation in anticipation of generalizing it (#20), so we can see if that generalization has any impact on the performance.
We bench two particular behaviors:
- Constructing a `TestResults` from an array of values
- This may not be perfect because in practice we're typically constructing them from a `Vec` of values, but I'm assuming that the iterators over arrays and `Vec`s have similar performance. (Let's hope that's true!)
- Finding the smallest (by total) in a `Vec<TestResults>`
The reason for benchmarking these is that the planned generalization will make the total result have a potentially different type than individual results, …
> Benchmark `TestResult`

- .github/workflows/ci.yml
This adds the `rust-toolchain` GitHub Action to explicitly install the appropriate tooling for each pass through the matrix of toolchains.
> Add explicit rust toolchain to GitHub Actions

- packages/push/src/error/stateful.rs
Add `const` to `new_boxed`. This hopefully fixes a problem where `nightly` wasn't building successfully, but I'm not sure what's going to happen on `stable` and `beta` now.
I'm assuming (based on a suggestion by @JustusFluegel) that there's some change in `nightly` that now allows functions that take `Box` values to be `const`, although I can't find anything online that would explain this change.
> Make `push::error::stateful::new_boxed` const

- Cargo.lock
- Cargo.toml
- packages/ec-core/Cargo.toml
- packages/ec-core/src/generation.rs
- packages/ec-core/src/operator/composable/and.rs
- packages/ec-core/src/operator/composable/map.rs
- packages/ec-core/src/operator/composable/repeat_with.rs
- packages/ec-core/src/operator/composable/then.rs
- packages/ec-core/src/operator/genome_extractor.rs
- packages/ec-core/src/operator/genome_scorer.rs
- packages/ec-core/src/operator/identity.rs
- packages/ec-core/src/operator/mod.rs
- packages/ec-core/src/operator/mutator/mod.rs
- packages/ec-core/src/operator/recombinator/mod.rs
- packages/ec-core/src/operator/selector/mod.rs
This adds an associated `Error` type for the `Operator` trait and changes the return type for `apply` to be a `std::result::Result` instead of an `anyhow::Result`.
This forced changes in anything that implemented `Operator`, as well as several things that acted on `Operator`s.
In several cases we had to add bounds saying that `anyhow::Error: From<X::Error>` to ensure that we could convert associated errors to `anyhow::Error`s. This (and other uses of `anyhow` in `ec_core`) should ultimately be removed as we transition to `miette` errors.
> Add associated `Error` type to `Operators`

- .helix/languages.toml
- .vscode/settings.json
I recently found in another project that rustfmt can behave weirdly without --edition 2021. This also mirrors the changes that were made to the helix config in the meantime in vscode
> Improved editor configs

- clippy.toml
This tells Clippy to not worry about the fact that we have multiple version of the `heck` crate. Hopefully we can remove this after we get updated versions of some other crates.
> Ignore duplicate version of `heck` crate

- Cargo.lock
- clippy.toml
- packages/push/Cargo.toml
- packages/push/benches/regression-evaluation.rs
This uses an evolved program that successfully solves a symbolic regression problem. This should provide a reasonable check for significant changes in the performance of a simple Push "function" that has no control flow.
Could be a part of addressing #201
> Add benchmark for evaluating floating point Push program

- .vscode/settings.json
Quick fix for a blunder in #226
> Actually use nightly in vscode for clippy lints.

- .vscode/settings.json
- packages/ec-core/src/distributions/collection.rs
- packages/ec-linear/src/genome/bitstring.rs
- packages/push/src/genome/plushy.rs
This eliminates a "Module name repetition" warning for the name `CollectionGenerator`.
Closes #220
> Rename `CollectionGenerator` to just `Generator`

- packages/push/src/instruction/int/abs.rs
- packages/push/src/instruction/int/mod.rs
- packages/push/src/instruction/int/negate.rs
- packages/push/tests/int.rs
In [one of the CI runs](https://github.com/unhindered-ec/unhindered-ec/actions/runs/9800496706/job/27062439279?pr=224) for #224, the `beta` check failed with the following message:
```
[push smallest <big_population_v2>] thread 'main' panicked at /rustc/64a1fe67112931359c7c9a222f08fd206255c2b5/library/core/src/num/mod.rs:359:5:
[push smallest <big_population_v2>] attempt to negate with overflow
```
The problem is the use of `i64::abs`, which fails with this error when taking the absolute value of `i64::MIN`. (The same thing would happen for any fixed-size signed integer type.) This is essentially the same problem as in #191, but a little indirect since it's `i64::abs` that's negating the value.
While I was fixing this, I also updated some comments in `Negate`. I also converted both this …
> Sporadic bug: "Attempt to negate with overflow" because of `i64::abs`

- packages/push/src/evaluation/cases.rs
This adds comments and doctests for all the methods in `Case` and `Cases` and their various trait implementations.
I also re-ordered the various functions in `Cases`, trying to group them by:
* Things that create sets of `Cases`
* Properties of `Cases` (like `len()`)
* Iterators over `Cases`
I found the tests to be a bit cleaner with the addition of `.inputs()` and `outputs()`, which return iterators over the inputs and outputs for a set of `Cases`.
I removed two TODO comments as we've created issues for those.
Closes #246
> Improve docs and tests for cases

- .github/workflows/ci.yml
- packages/ec-core/src/lib.rs
- packages/ec-core/src/operator/selector/tournament.rs
- packages/ec-linear/src/lib.rs
- packages/push-macros/src/lib.rs
- packages/push-macros/src/push_state/printing/generate_builder.rs
- packages/push/src/evaluation/cases/iter.rs
- packages/push/src/evaluation/cases/mod.rs
- scripts/cargo-rustdoc-clippy
This runs Clippy on all the doctests, and includes checking for `unused` elements.
This generated several warnings, which we also cleaned up.
Closes #255
> Clean up Clippy warnings in doctests

- packages/ec-core/src/operator/selector/best.rs
- packages/ec-core/src/operator/selector/mod.rs
- packages/ec-core/src/operator/selector/random.rs
- packages/ec-core/src/operator/selector/weighted.rs
- packages/ec-core/src/operator/selector/worst.rs
This adds `proptest` for all the selectors mentioned in #240:
- #242
- #243 
- #244 
I also added a new `Worst` selector because that made it easier to write a reasonable test for the `Weighted` selector. That might also be useful in some EC contexts where, for example, we might want to select the worst individual for removal from the population.
We had talked about doing these in separate PRs, but in the end it was so straightforward that I figured I'd just do them all as a batch.
Closes: #240 
Closes: #242 
Closes: #243 
Closes: #244
> Add proptest tests for selectors

- Cargo.toml
- packages/ec-linear/examples/count_ones/args.rs
- packages/ec-linear/examples/count_ones/main.rs
- packages/ec-linear/examples/hiff/args.rs
- packages/ec-linear/examples/hiff/main.rs
- packages/push/Cargo.toml
- packages/push/examples/complex_regression/args.rs
- packages/push/examples/complex_regression/main.rs
- packages/push/examples/simple_regression/args.rs
- packages/push/examples/simple_regression/main.rs
This renames `num_generations` to `max_generations` in all the `clap` configurations, and adds `-g` as the short form for everyone.
This also renames `Args` to `CliArgs` in all the examples and updates the CI configuration so we just have a single configuration set.
Closes #189 
Closes #190
> Rename `num-generations` to `max-generations`, and `Args` to `CliArgs`

- .github/workflows/ci.yml
This applys the suggestions about our gh workflow from the static analysis tool called [zizmor](https://github.com/woodruffw/zizmor), which is meant to find (security-related) issues in github workflows, such as code injection or token stealing by creation of malicious pr's
> Apply suggestions from zizmor static analysis tool

- packages/ec-core/src/operator/selector/lexicase.rs
- packages/ec-core/src/test_results.rs
Also adds the `is_empty()` method on the same type since clippy complains if we have a `len()` without a `.is_empty()`
Closes #238
> Add `TestResults::len(&self) -> usize` method

- packages/push/src/instruction/int/mod.rs
This fixes a new clippy lint that popped up in recent nightly ci runs. Together with #305 this will fix all the broken nightly clippy lints.
> Remove useless conversion to same type (nightly clippy lint fix)

- .github/workflows/ci.yml
This enables us to check for broken intra-doc links inside our documentation.
Closes #213
> Build rustdoc in ci

- packages/push/Cargo.toml
- packages/push/src/instruction/bool.rs
- packages/push/src/instruction/float.rs
- packages/push/src/instruction/int/mod.rs
We need to display the values being pushed when we use a `Push(T)` instruction for `BoolInstruction`, `IntInstruction`, or `FloatInstruction`. This uses the `#[strum(to_string = "Push({0})")]` annotation to get each of these to display with a form like `Float-Push(1)`.
~~Adding these failed with the versions of `strum` and `strum-macros` that we were using at that point. I ran `cargo update` to update all the dependencies, including those for `strum` and `strum-macros`. That fixed the display, but unfortunately lead to a Clippy warning "multiple versions for dependency `heck`: 0.4.1, 0.5.0", which causes all the checks to fail on this PR.~~
Edit: Since this was laying around for so long I (@JustusFluegel ) just reset-ted to the main branch and cherry-picked the relevant commit. The heck …
> Add specific `strum(to_string = …)` for Push `Push` instructions

- packages/push-macros/src/push_state/printing/generate_builder.rs
- packages/push/src/push_vm/program.rs
- packages/push/src/push_vm/stack.rs
This also prevents deadlocks/crashes/oom errors in case of infinite or very large iterators
> Change stack try_extend impl to avoid additional heap allocations 

- packages/ec-core/src/operator/selector/best.rs
- packages/ec-core/src/operator/selector/mod.rs
- packages/ec-core/src/operator/selector/tournament.rs
- packages/ec-core/src/population.rs
- packages/ec-core/src/test_results.rs
- packages/ec-core/src/weighted/weighted_pair.rs
- packages/push/src/push_vm/push_state.rs
- packages/push/src/push_vm/stack.rs
- packages/push/tests/float.rs
Also removes some superfluous collects using iterator equality and some unneeded vecs in other places
> Implement Population trait via a blanket impl for any objects that have a sized iterator from it's reference and not just for `Vec<T>`

- packages/ec-macros/Cargo.toml
Removes `publish = false` from the ec_macros package, such that we can publish it to a (local) registry
> Make `ec-macros` publishable

- packages/ec-core/README.md
- packages/ec-linear/README.md
- packages/ec-macros/README.md
- packages/push-macros/README.md
- packages/push/README.md
This adds some basic readme placeholders since we need those to publish the crates as packages to a (local) registry. We should definitely create some more proper ones sometime soon.
> Add readme placeholders

- Cargo.lock
- Cargo.toml
- packages/ec-core/src/distributions/choices.rs
- packages/ec-core/src/distributions/conversion.rs
- packages/ec-core/src/distributions/wrappers/choose_cloning.rs
- packages/ec-core/src/distributions/wrappers/mod.rs
- packages/ec-core/src/distributions/wrappers/owned.rs
- packages/ec-core/src/distributions/wrappers/slice_cloning.rs
This also required changing references to `rand::distr::Slice` to `rand::distr::slice::Choose`, and is a requirement to publish the local packages to a (local) registry.
> Update `rand` to `beta.3`

- packages/push/proptest-regressions/instruction/common/cmp/greater_than.txt
- packages/push/src/instruction/common/cmp/equal.rs
- packages/push/src/instruction/common/cmp/greater_than.rs
- packages/push/src/instruction/common/cmp/greater_than_equal.rs
- packages/push/src/instruction/common/cmp/less_than.rs
- packages/push/src/instruction/common/cmp/less_than_equal.rs
- packages/push/src/instruction/common/cmp/mod.rs
- packages/push/src/instruction/common/cmp/not_equal.rs
- packages/push/src/instruction/common/mod.rs
- packages/push/src/instruction/int/clamp.rs
This implements an `Equal` and `NotEqual` instructions on stacks with types that implement `Equal`, and all the standard comparison operators (`LessThan`, `LessThanEquals`, etc.) on stacks with types that implement `Ord`.
This is satisfying part of #350.
> Add push instructions for equality and comparison tests

- .vscode/settings.json
- clippy.toml
- packages/ec-linear/src/mutator/umad.rs
[The original UMAD paper](https://doi.org/10.1145/3205455.3205603) randomly decides whether to put a newly added gene on the left or right side of the current gene. We didn't actually provide that functionality, and this fixes that.
Hopefully our UMAD implementation now matches (or can match with the correct parameters) the published definition.
While we were here, we also added documentation and examples for `Umad`.
> Further align our `Umad` implementation with the UMAD paper

- packages/ec-linear/src/genome/bitstring.rs
- packages/ec-linear/src/recombinator/crossover.rs
- packages/ec-linear/src/recombinator/errors.rs
- packages/ec-linear/src/recombinator/two_point_xo.rs
- packages/ec-linear/src/recombinator/uniform_xo.rs
This pull request focuses on cleaning up and generalizing the bitstring crossover implementation. The primary goal is to centralize and standardize error handling for gene and segment access during crossover operations by introducing new, more robust generic error types. This refactoring also involves removing outdated `Vec<T>`-specific crossover logic in favor of a more generalized `Crossover` trait implementation for `Vec<T>`, leading to a cleaner, more maintainable, and extensible codebase for genetic algorithms.
* **Standardized Crossover Error Handling**: The `Bitstring`'s `Crossover` trait implementation has been refactored to use a new, more generic `MultipleGeneAccess` error type, replacing the specific `GeneAccess` and `GeneAccessRange` structs. This change centralizes and …
> Clean up bitstring impl of crossover
