- packages/push-macros/src/push_state/printing/generate_builder.rs
- packages/push/src/instruction/bool.rs
- packages/push/tests/float.rs
- packages/push/tests/int.rs
> Add with no program method to pushstate builder

- packages/push/src/instruction/float.rs
- packages/push/tests/float.rs
This adds `LessThan` and `GreaterThan`, and `LessThanOrEqual` and `GreaterThanOrEqual`, along with tests.
> Add float inequality instructions (<, >, <=, >=)

- packages/push/tests/float.rs
- packages/push/tests/int.proptest-regressions
- packages/push/tests/int.rs
> Use dedicated builder methods where applicable

- Cargo.toml
- packages/ec-core/Cargo.toml
- packages/ec-core/src/individual/mod.rs
- packages/ec-core/src/lib.rs
- packages/ec-core/src/population.rs
- packages/ec-ga-cli/Cargo.toml
- packages/ec-ga-cli/src/bin_original/ga.rs
- packages/ec-ga-cli/src/bin_original/main.rs
- packages/ec-ga-cli/src/bin_original/pushgp.rs
- packages/ec-ga-cli/src/main.rs
- packages/ec-linear/Cargo.toml
- packages/ec-linear/src/genome/demo_scorers.rs
- packages/ec-linear/src/lib.rs
- packages/ec-push-cli/Cargo.toml
- packages/ec-push-cli/src/main.rs
- packages/push/Cargo.toml
- packages/push/examples/complex_regression/main.rs
- packages/push/src/lib.rs
- packages/rust-lexicase/Cargo.toml
- packages/rust-lexicase/src/lib.rs
Closes #41 
as well as Closes #38 since I added the corresponding lint here and fixed the single instance where it was used.
> Move lints to a workspace config

- packages/ec-push-cli/src/main.rs
- packages/push/examples/complex_regression/main.rs
- packages/push/src/genome/plushy.rs
- packages/push/src/instruction/variable_name.rs
- packages/push/src/push_vm/push_state.rs
> Impl From<VariableName> for PushInstruction and change usages where applicable

- packages/push-macros/src/push_state/printing/generate_builder.rs
> Simplify .with_program generics

- packages/push/src/genome/plushy.rs
> Disable umad test for now

- packages/ec-push-cli/src/main.rs
- packages/push/examples/complex_regression/main.rs
- packages/push/src/genome/plushy.rs
- packages/push/src/instruction/variable_name.rs
- packages/push/src/lib.rs
- packages/push/src/list_into.rs
- packages/push/src/push_vm/program.rs
- packages/push/src/push_vm/push_state.rs
> Impl `vec_into!`, `arr_into!` macros

- packages/ec-push-cli/src/main.rs
- packages/push/examples/complex_regression/main.rs
- packages/push/src/genome/plushy.rs
- packages/push/src/instruction/bool.rs
- packages/push/src/instruction/mod.rs
- packages/push/src/instruction/variable_name.rs
- packages/push/src/lib.rs
- packages/push/src/list_into.rs
- packages/push/src/push_vm/program.rs
- packages/push/src/push_vm/push_state.rs
- packages/push/src/push_vm/stack.rs
Based on #56 so merge after that
> Remove spaces in comments (introduced by #47)

- Cargo.lock
- Cargo.toml
- packages/ec-push-cli/src/main.rs
- packages/push-macros/Cargo.toml
- packages/push-macros/src/push_state/printing/generate_builder.rs
- packages/push/Cargo.toml
- packages/push/examples/complex_regression/main.rs
- packages/push/src/genome/plushy.rs
- packages/push/src/lib.rs
- packages/push/src/list_into.rs
- packages/push/src/push_vm/program.rs
- packages/push/src/push_vm/push_state.rs
Document all decl macros (those declared with `macro_rules!`), adding railroad diagrams
> Document macros

- .github/workflows/ci.yml
This change errors on any warnings in ci from either clippy, cargo build or cargo test.
> Error on warnings in ci

- .github/workflows/ci.yml
- Cargo.toml
Runs examples in ci. It may be worth to have  a look at https://crates.io/crates/example-runner-cli to understand the config options.
> Example smoke tests

- .github/workflows/ci.yml
- packages/ec-linear/src/mutator/umad.rs
> Add --all-targets to ci

- packages/ec-core/src/generator/collection.rs
> Remove Self: Sized bound on collection generator to_* methods

- packages/ec-linear/src/mutator/umad.rs
> Allow UMAD to add new elements to empty lists

- packages/ec-linear/examples/count_ones/main.rs
- packages/ec-linear/examples/hiff/main.rs
- packages/push/examples/complex_regression/args.rs
- packages/push/examples/complex_regression/main.rs
- packages/push/examples/simple_regression/args.rs
- packages/push/examples/simple_regression/main.rs
- packages/push/src/genome/plushy.rs
Closes #103  (see [here](https://github.com/JustusFluegel/rust-ga/compare/rand_distrb_trait...JustusFluegel:rust-ga:cleanup_examples) for diff) (based on #94 )
> Cleanup examples

- clippy.toml
- packages/ec-core/src/operator/selector/recursive_weighted.rs
- packages/ec-core/src/operator/selector/weighted.rs
As discussed on stream here a version of the recursive weighted selector where I've tried to move away from generics on the structs as much as possible.
> Less restrictive weighted generics

- packages/ec-core/src/generation.rs
> Add `Generation::into_population` method

- packages/ec-core/src/test_results.rs
- packages/push/examples/complex_regression/main.rs
- packages/push/examples/median/main.rs
- packages/push/examples/simple_regression/main.rs
- packages/push/examples/smallest/main.rs
> Change Error and Score structs to be newtypes

- packages/push/src/push_vm/stack.rs
> Fix new clippy lint about useless continue; statement

- packages/ec-core/src/operator/selector/lexicase.rs
> Make lexicase use checked indexing

- CONTRIBUTING.md
To aid @NicMcPhee 's course registry so he can look up the process again if he gets lost.
> Document the publishing process

- Cargo.lock
- Cargo.toml
> Bump rand to stable release

- packages/push/src/instruction/bool.rs
- packages/push/src/instruction/exec/mod.rs
- packages/push/src/instruction/float.rs
- packages/push/src/instruction/int/abs.rs
- packages/push/src/instruction/int/clamp.rs
- packages/push/src/instruction/int/mod.rs
- packages/push/src/instruction/int/negate.rs
- packages/push/src/instruction/printing/char.rs
- packages/push/src/instruction/variable_name.rs
Makes it more straightforward to use them
> Create creation functions for all instructions
